### ISSUE TITLE
ValueError - swing_mode_enum (Hassio 0.83.2)

### ISSUE THREAD

**Issue by kegra** [NeoAcheron/midea-ac-py#1]
Hassio 0.83.2 running over Ubuntu 18.04
all files are in place , after restart i get:

Error while setting up platform midea
Traceback (most recent call last):
File “/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py”, line 128, in _async_setup_platform
SLOW_SETUP_MAX_WAIT, loop=hass.loop)
File “/usr/local/lib/python3.6/asyncio/tasks.py”, line 358, in wait_for
return fut.result()
File “/config/custom_components/climate/midea.py”, line 50, in async_setup_platform
entities = [MideaClimateDevice(device, temp_step) for device in devices]
File “/config/custom_components/climate/midea.py”, line 50, in 
entities = [MideaClimateDevice(device, temp_step) for device in devices]
File “/config/custom_components/climate/midea.py”, line 66, in init
device.refresh()
File “/config/deps/lib/python3.6/site-packages/midea/device.py”, line 82, in refresh
self.update(response)
File “/config/deps/lib/python3.6/site-packages/midea/device.py”, line 108, in update
self._swing_mode = swing_mode_enum(res.swing_mode)
File “/usr/local/lib/python3.6/enum.py”, line 291, in call
return cls.new(cls, value)
File “/usr/local/lib/python3.6/enum.py”, line 533, in new
return cls.missing(value)
File “/usr/local/lib/python3.6/enum.py”, line 546, in missing
raise ValueError("%r is not a valid %s" % (value, cls.name))
ValueError: 48 is not a valid swing_mode_enum

**Comment by kegra** [comment]
yes ! thank you ! just for the record if anyone is searching air-condition model Omnia Plus Inventor is supported from your add on.

**Comment by NeoAcheron** [comment]
Awesome! I think its time to make a Wiki to add supported devices!
