### ISSUE TITLE
[feature request] CLI

### ISSUE THREAD

**Issue by asquelt** [NeoAcheron/midea-ac-py#10]
please consider adding a small CLI, where you can test all settings against the unit without installing Hass.

**Comment by NeoAcheron** [comment]
Hi @asquelt 
There are instruction in the Wiki on how to launch the component without Hass or Home Assistant. 

Please see here: https://github.com/NeoAcheron/midea-ac-py/wiki/Basic-Usage

I'm reluctant to add a CLI now, it's another part to maintain while the library is still unstable. If you really need a command-line, try using the ruby library, which is purely a CLI implementation.

**Comment by asquelt** [comment]
i've noticed that ruby version uses different commands that this library. that's why i wanted to compare them on my unit (ie. fan speed doesn't work in ruby lib).

**Comment by NeoAcheron** [comment]
I just updated the documentation, I realized that they were slightly out of date.

**Comment by asquelt** [comment]
thank you.
this seems to be working with my model (Kaisai).
i'll try to integrate it with my Domoticz and get back with plugin file.
