### ISSUE TITLE
No devices on Home Assistant

### ISSUE THREAD

**Issue by gsalvati** [NeoAcheron/midea-ac-py#9]
Dears, 

I installed the module and configured it.
No erros in log, but no devices showed in States or Interface.
What I need to do?

Home Assistant
0.83.2

Using master from GIT

**Comment by NeoAcheron** [comment]
Hi there,

You should be seeing at least some debug about the devices returned. What kinds of appliances are you trying to control?

**Comment by gsalvati** [comment]
Hi,

I discovered my appliances at home are compatible with netHome APP (https://play.google.com/store/apps/details?id=com.idelan.NetHome) not netHome plus.

Do you know how to integrate with this API?

Thanks

**Comment by NeoAcheron** [comment]
Hi @gsalvati,

Unfortunately I'm not able to say if it would be possible to support this app at all. It might be using a different cloud API, I tried the app you mentioned above and my air conditioners are not listed as supported.
